name: "Terraform Plan"

trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:

- script: |
    cd ./Example
    terraform init
    terraform plan -out=terraform.tfplan
  displayName: 'Terraform Plan'